apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: health-db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: healthy
          volumeMounts:
            - name: pg-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-storage
          emptyDir: {}
--- 
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
